name: CD with Gradle (Direct JAR)

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build with Gradle
        run: ./gradlew clean build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/tk-univ"
          strip_components: 2

      - name: Run Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            APP_DIR="/home/ubuntu/tk-univ"
            JAR_NAME=$(ls $APP_DIR/libs | grep .jar | grep -v "plain" | head -n 1)
            
            echo "Stop existing application on port 8080"
            sudo fuser -k 8080/tcp || true
            
            echo "Start New JAR with Secrets"
            cd $APP_DIR
            
            nohup java -jar \
              -Dspring.profiles.active=prod \
              -DPROD_DB_URL="${{ secrets.PROD_DB_URL }}" \
              -DPROD_DB_USERNAME="${{ secrets.PROD_DB_USERNAME }}" \
              -DPROD_DB_PASSWORD="${{ secrets.PROD_DB_PASSWORD }}" \
              -DPROD_JWT_SECRET="${{ secrets.PROD_JWT_SECRET }}" \
              -DPROD_INIT_EMAIL="${{ secrets.PROD_INIT_EMAIL }}" \
              -DLOCAL_EMAIL="${{ secrets.EMAIL }}" \
              -DAPP_PASSWORD="${{ secrets.APP_PASSWORD }}" \
              libs/$JAR_NAME > app.log 2>&1 &
            
            echo "Deployment set to background."